const coverNestorEnBloque =
  "https://audio-assets1.web.app/portadas/Nestor%20en%20Bloque.jpg";
export const TrackListNestorEnBloque = [
  {
    name: "Mi Unico Amor",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Mi%20%C3%9Anico%20Amor.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Amigos En La Distancia",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Amigos%20en%20la%20distancia.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Te Fuiste Sin Pensar",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Te%20Fuiste%20Sin%20Pensar.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Fuiste Mi Luz",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Fuiste%20Mi%20Luz.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Perdoname",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Perdoname.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Una Calle Nos Separa",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Una%20Calle%20Nos%20Separa.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "te quiero a ti",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Te%20Quiero%20a%20Ti.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Mi Promesa",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Mi%20Promesa.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Estoy Buscando Un Amor",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Estoy%20Buscando%20un%20Amor.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Yo Mañana",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Yo%20Ma%C3%B1ana.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Estoy Solo",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Estoy%20Solo.mp3",
    cover: coverNestorEnBloque,
  },  
  {
    name: "Te Soñé Mas De Una Vez",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Te%20So%C3%B1%C3%A9%20Mas%20de%20una%20Vez.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Dejenlá Que llore",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Dejenl%C3%A1%20Que%20Llore.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Déjate Venir",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/D%C3%A9jate%20Venir.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Adiós, Adiós Amor",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Adi%C3%B3s,%20Adi%C3%B3s%20Amor.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Primer Amor",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Primer%20Amor.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Donde Estás",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Donde%20Est%C3%A1s.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Mírame Una Vez Más",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/M%C3%ADrame%20una%20Vez%20M%C3%A1s.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Quieres Ser Mi Amante",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Quieres%20Ser%20Mi%20Amante.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Explícame Mi Amor",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Expl%C3%ADcame%20Mi%20Amor.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Te Marchaste De Mí",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Te%20Marchaste%20de%20M%C3%AD.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "No Olvidaré",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/No%20Olvidar%C3%A9.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "LLorando Su Recuerdo",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Llorando%20Su%20Recuerdo.mp3",
    cover: coverNestorEnBloque,
  },
  {
    name: "Pagaré Por Mi Error",
    artist: "Nestor en Bloque",
    url: "https://audio-assets1.web.app/audio/nestor%20en%20bloque/Pagar%C3%A9%20por%20Mi%20Error.mp3",
    cover: coverNestorEnBloque,
  },
];
