const coverSombras =
  "https://audio-assets1.web.app/portadas/grupo%20sombras.jpg";
export const TrackListSombras = [
  {
    name: "La ventanita",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/La%20Ventanita.mp3",
    cover: coverSombras,
  },
  {
    name: "Lucerito",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Lucerito.mp3",
    cover: coverSombras,
  },
  {
    name: "El perfume de tu piel",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/El%20perfume%20de%20tu%20piel.mp3",
    cover: coverSombras,
  },
  {
    name: "Niña Caprichosa",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Ni%C3%B1a%20Caprichosa.mp3",
    cover: coverSombras,
  },
  {
    name: "El Regalito",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/El%20Regalito.mp3",
    cover: coverSombras,
  },
  {
    name: "Pega la Vuelta",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Pega%20la%20Vuelta.mp3",
    cover: coverSombras,
  },
  {
    name: "Boquita de Caramelo",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Boquita%20de%20Caramelo.mp3",
    cover: coverSombras,
  },
  {
    name: "Puertas Cerradas",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Puertas%20Cerradas.mp3",
    cover: coverSombras,
  },
  {
    name: "P.D Yo Te Amo",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/P.D%20yo%20te%20Amo.mp3",
    cover: coverSombras,
  },
  {
    name: "En Pie de Guerra",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/En%20pie%20de%20guerra.mp3",
    cover: coverSombras,
  },
  {
    name: "La Chica del Baile",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/La%20Chica%20Del%20Baile.mp3",
    cover: coverSombras,
  },
  {
    name: "Veneno para Olvidar",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Veneno%20Para%20Olvidar.mp3",
    cover: coverSombras,
  },
  {
    name: "La Malagata",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/La%20Malagata.mp3",
    cover: coverSombras,
  },
  {
    name: "Inolvidable",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Inolvidable.mp3",
    cover: coverSombras,
  },
  {
    name: "Dime Amor",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Dime%20amor.mp3",
    cover: coverSombras,
  },
  {
    name: "Mienteme",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Mi%C3%A9nteme.mp3",
    cover: coverSombras,
  },
  {
    name: "Triste Novela",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Triste%20Novela.mp3",
    cover: coverSombras,
  },
  {
    name: "Otra Noche de Amor",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Otra%20noche%20de%20amor.mp3",
    cover: coverSombras,
  },
  {
    name: "Porque Yo",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Porque%20Yo.mp3",
    cover: coverSombras,
  },
  {
    name: "Beso a Beso",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Beso%20a%20Beso.mp3",
    cover: coverSombras,
  },
  {
    name: "Una Copita Mas",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Una%20Copita%20Mas.mp3",
    cover: coverSombras,
  },
  {
    name: "Añoranzas/Todas las Noches",
    artist: "Daniel Agostini",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/A%C3%B1oranzas%20Todas%20las%20Noches.mp3",
    cover: coverSombras,
  },
  {
    name: "Arco Iris",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Arco%20Iris.mp3",
    cover: coverSombras,
  },
  {
    name: "Soy",
    artist: "Grupo sombras",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/Soy.mp3",
    cover: coverSombras,
  },
  {
    name: "El Humo del Cigarrillo",
    artist: "Daniel Agostini",
    url: "https://audio-assets1.web.app/audio/grupo%20sombras/El%20Humo%20del%20Cigarrillo.mp3",
    cover: coverSombras,
  },
];
